# Generated by Django 5.0.6 on 2024-07-28 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='full_name',
            field=models.CharField(default='chef', max_length=255),
        ),
    ]
