# Generated by Django 5.0.6 on 2024-07-29 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_profile_full_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
